# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 09:31
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticklist', '0002_auto_20171113_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticklist',
            name='end_date',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(models.IntegerField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(datetime.datetime(2017, 11, 14, 9, 31, 32, 994813))]))]),
        ),
        migrations.AlterField(
            model_name='ticklist',
            name='start_date',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(datetime.datetime(2017, 11, 14, 9, 31, 32, 994813))]),
        ),
    ]
