# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 10:28
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticklist', '0003_auto_20171114_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticklist',
            name='end_date',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(models.IntegerField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(datetime.datetime(2017, 11, 14, 10, 28, 6, 865125))]))]),
        ),
        migrations.AlterField(
            model_name='ticklist',
            name='start_date',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(datetime.datetime(2017, 11, 14, 10, 28, 6, 865125))]),
        ),
    ]
