# Generated by Django 2.0.1 on 2018-01-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('bill', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'bill',
            },
        ),
    ]
