# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='member',
            field=models.IntegerField(default=0),
        ),
    ]
