# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='job_title',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='url',
            new_name='joiningyear',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='member',
        ),
        migrations.AddField(
            model_name='profile',
            name='gphone',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='room_num',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
