# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 09:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20171115_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='room_num',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator(regex='^[n|o]\\d\\d\\d$')]),
        ),
    ]
